---
- name: Ensure Wordfence CLI configuration directory exists
  ansible.builtin.file:
    path: /etc/wordfence
    state: directory
    owner: root
    group: root
    mode: '0750'

- name: Ensure Wordfence CLI cache directory exists
  ansible.builtin.file:
    path: /var/cache/wordfence
    state: directory
    owner: root
    group: root
    mode: '0750'

- name: Write Wordfence CLI configuration file
  ansible.builtin.template:
    src: wordfence-cli.ini.j2
    dest: /etc/wordfence/wordfence-cli.ini
    owner: root
    group: root
    mode: '0640'
  no_log: true

- name: Install Wordfence S3 scan runner
  ansible.builtin.template:
    src: wordfence-scan-to-s3.j2
    dest: /usr/local/sbin/wordfence-scan-to-s3
    owner: root
    group: root
    mode: "0750"
    validate: /usr/bin/bash -n %s
