---
- name: Install Wordfence CLI
  import_tasks: install.yml
  tags: [wordfence, wordfence-install]

- name: Configure Wordfence CLI
  import_tasks: configure.yml
  tags: [wordfence, wordfence-configure]

- name: Schedule Wordfence CLI scans
  import_tasks: schedule.yml
  tags: [wordfence, wordfence-schedule]
